## 应用名称
#spring.application.name=mybatisplus
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
logging:
  level:
    root: warn
    com.jinchao.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'
mybatis-plus:
  mapper-locations:
  - com/mp/mapper/*
  global-config:
    db-config:
      id-type: uuid
  config-location: classpath:mybatis-config.xml

